# Generated by Django 4.0.2 on 2022-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='평점'),
        ),
    ]
