# Generated by Django 4.0.2 on 2022-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.TextField(default='', verbose_name='찜한 아이템 번호'),
        ),
    ]
