# Generated by Django 4.0.2 on 2022-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numItemSharing',
            field=models.IntegerField(default=0, verbose_name='판매중인 아이템 수'),
        ),
    ]
