# Generated by Django 4.0.2 on 2022-03-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_numitemsharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sigungu',
            field=models.CharField(default='', max_length=15, verbose_name='시군구'),
        ),
    ]
