# Generated by Django 4.0.2 on 2022-02-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='like',
            field=models.IntegerField(default=0, verbose_name='찜한 사람 수'),
        ),
    ]
