# Generated by Django 4.0.2 on 2022-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='평점'),
        ),
        migrations.AddField(
            model_name='item',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='평가 수'),
        ),
    ]
