# Generated by Django 4.0.2 on 2022-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_rate_item_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.FloatField(default=0, verbose_name='평점'),
        ),
    ]
