# Generated by Django 4.0.2 on 2022-02-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sigungu',
            field=models.CharField(default=2, max_length=15, verbose_name='시군구'),
            preserve_default=False,
        ),
    ]
