# Generated by Django 4.0.2 on 2022-02-20 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_sigungu'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likedUser',
            field=models.TextField(default='', verbose_name='찜한 유저들'),
        ),
        migrations.AddField(
            model_name='item',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='올린 시간'),
        ),
    ]
