# Generated by Django 4.0.2 on 2022-03-02 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_writername'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='종료시간'),
        ),
        migrations.AddField(
            model_name='item',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='시간시간'),
        ),
    ]
