# Generated by Django 4.0.2 on 2022-02-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='writerName',
            field=models.CharField(default='', max_length=15, verbose_name='작성자 닉네임'),
        ),
    ]
