# Generated by Django 4.0.2 on 2022-03-12 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_numorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='writerName',
            new_name='nameWriter',
        ),
    ]
