# Generated by Django 4.0.2 on 2022-03-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ordernumber', models.AutoField(primary_key=True, serialize=False)),
                ('seller', models.IntegerField(verbose_name='판매자번호')),
                ('buyer', models.IntegerField(verbose_name='구매자번호')),
                ('itemnumber', models.IntegerField(verbose_name='아이템번호')),
                ('startTime', models.DateTimeField(verbose_name='시작시간')),
                ('endTime', models.DateTimeField(verbose_name='종료시간')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('buyerName', models.CharField(max_length=30, verbose_name='구매자 이름')),
                ('buyerPhone', models.TextField(verbose_name='구매자 휴대폰번호')),
                ('buyerEmail', models.TextField(verbose_name='구매자 이메일')),
                ('buyerDemand', models.TextField(verbose_name='구매자 요청사항')),
                ('confirmTime', models.DateTimeField(verbose_name='확정시간')),
            ],
        ),
    ]
