# Generated by Django 4.0.2 on 2022-03-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='endTime',
            field=models.TextField(verbose_name='종료시간'),
        ),
        migrations.AlterField(
            model_name='order',
            name='startTime',
            field=models.TextField(verbose_name='시작시간'),
        ),
    ]
