# Generated by Django 4.0.2 on 2022-03-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_confirmtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reviewWritten',
            field=models.BooleanField(default=False, verbose_name='리뷰 작성 여부'),
        ),
    ]
